### ISSUE TITLE
Doesn't work (anymore?) :(

### ISSUE THREAD

**Issue by PanMan** [wiseman/webflight-gamepad#1]
Hi!
This doesn't seem to work anymore :(
I installed it in webflight, the console says the plugin is loaded, and (in Firefox) says my gamepad is detected. However, after that, nothing happens.
In Chrome it says my gamepad isn't supported.
The test page at http://www.html5rocks.com/en/tutorials/doodles/gamepad/gamepad-tester/tester.html works both in Chrome and Firefox.
I guess this has to do with changes in the Gamepad API the last 2 years?

**Comment by wadedos** [comment]
Try this fork, https://github.com/wadeos/webflight-gamepad

**Comment by wiseman** [comment]
@wadeos, if you have a working version would you like to submit a pull request and I'll merge your code?

**Comment by wadedos** [comment]
Done. I tested it using a Logitech Extreme 3D Pro.

**Comment by wiseman** [comment]
I've merged Wade's code.  @PanManAms, Does this solve your problem?

**Comment by PanMan** [comment]
It sounds like it should :). But I don't have the drones here anymore: I did a temporary project to control multiple drones at once.
Has anybody tested this with a recent browser and drone? I might be able to get one again to try, but don't have one here atm.

**Comment by noerw** [comment]
for me it works with recent firefox and chromium, closing
