### ISSUE TITLE
Remapping buttons and axis instructions?

### ISSUE THREAD

**Issue by anthonySmithTraclabs** [wiseman/webflight-gamepad#2]
Do you have any guidance about how to remap the buttons and axis for a non Logitech gamepad?

**Comment by wiseman** [comment]
@anthonySmithTraclabs I have some time to take a look at this if you're still interested.

(Is your name referencing TRACLabs in Houston?  I used to work with those guys a bit, a long time ago.)

**Comment by anthonySmithTraclabs** [comment]
Yes, I work for TRACLabs in Houston..small world!  I am definitely still
interested in this.

-Anthony

**Comment by noerw** [comment]
In my fork a custom configuration can be defined in the ardrone-webflight `config.js`. 

Just add an object `gamepad` to the config.js and fill it according to the [readme](https://github.com/noerw/webflight-gamepad#configuration)

**Comment by noerw** [comment]
this is now merged, closing
