### ISSUE TITLE
npm warning message

### ISSUE THREAD

**Issue by Sasounet** [wiseman/webflight-gamepad#5]
I installed webflight-gamepad without problem on a mac (there was that strange xcode license agreement)

But when I try to use "npm install" I get the following warning message:

npm WARN package.json webflight-gamepad@0.0.1 license should be a valid SPDX license expression

The next step is to link "gamepad" from webflight-gamepad folder into the ardrone-webflight/plugins but there are no files named "gamepad"

HELP!!

François

**Comment by Sasounet** [comment]
Ok I figured it out. Sorry.

**Comment by wiseman** [comment]
Francois, what was the solution (for the benefit of anyone else who runs into the same problem)?

**Comment by Sasounet** [comment]
Well, there was no solution as I realized it went correctly the first time. Yes, there was a warning message but it did not stop the process. Everything was fine so I closed the issue.

I thought there was a problem because I misinterpret what the link command was supposed to do. My Unix is a bit rusty.

François
